/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DevelopmentProject {
  'id' : bigint,
  'currentPhase' : string,
  'targetCompletionDate' : [] | [bigint],
  'name' : string,
  'description' : string,
  'propertyId' : bigint,
  'budget' : bigint,
  'startDate' : bigint,
}
export interface Property {
  'id' : bigint,
  'status' : PropertyStatus,
  'propertyType' : PropertyType,
  'acquisitionDate' : bigint,
  'name' : string,
  'address' : string,
  'estimatedCompletionDate' : [] | [bigint],
}
export type PropertyStatus = { 'completed' : null } |
  { 'development' : null } |
  { 'planning' : null };
export type PropertyType = { 'commercial' : null } |
  { 'residential' : null } |
  { 'mixedUse' : null };
export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'name' : string,
  'dueDate' : [] | [bigint],
  'description' : string,
  'projectId' : bigint,
  'priority' : TaskPriority,
  'assignedTeamMember' : [] | [Principal],
}
export type TaskPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type TaskStatus = { 'notStarted' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface TeamMember {
  'id' : Principal,
  'name' : string,
  'role' : string,
  'email' : string,
  'projectIds' : Array<bigint>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'department' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTeamMember' : ActorMethod<[Principal, string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<
    [string, string, bigint, bigint, [] | [bigint], string, bigint],
    bigint
  >,
  'createProperty' : ActorMethod<
    [string, string, PropertyType, PropertyStatus, bigint, [] | [bigint]],
    bigint
  >,
  'createTask' : ActorMethod<
    [
      string,
      string,
      [] | [Principal],
      TaskStatus,
      TaskPriority,
      [] | [bigint],
      bigint,
    ],
    bigint
  >,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'deleteProperty' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAllProjects' : ActorMethod<[], Array<DevelopmentProject>>,
  'getAllProperties' : ActorMethod<[], Array<Property>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProject' : ActorMethod<[bigint], [] | [DevelopmentProject]>,
  'getProperty' : ActorMethod<[bigint], [] | [Property]>,
  'getTask' : ActorMethod<[bigint], [] | [Task]>,
  'getTeamMember' : ActorMethod<[Principal], [] | [TeamMember]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeTeamMember' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProject' : ActorMethod<
    [bigint, string, string, bigint, bigint, [] | [bigint], string, bigint],
    boolean
  >,
  'updateProperty' : ActorMethod<
    [
      bigint,
      string,
      string,
      PropertyType,
      PropertyStatus,
      bigint,
      [] | [bigint],
    ],
    boolean
  >,
  'updateTask' : ActorMethod<
    [
      bigint,
      string,
      string,
      [] | [Principal],
      TaskStatus,
      TaskPriority,
      [] | [bigint],
      bigint,
    ],
    boolean
  >,
  'updateTeamMember' : ActorMethod<
    [Principal, string, string, string, Array<bigint>],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];