/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'commercial' : IDL.Null,
  'residential' : IDL.Null,
  'mixedUse' : IDL.Null,
});
export const PropertyStatus = IDL.Variant({
  'completed' : IDL.Null,
  'development' : IDL.Null,
  'planning' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const TaskPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const DevelopmentProject = IDL.Record({
  'id' : IDL.Nat,
  'currentPhase' : IDL.Text,
  'targetCompletionDate' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'propertyId' : IDL.Nat,
  'budget' : IDL.Nat,
  'startDate' : IDL.Nat,
});
export const Property = IDL.Record({
  'id' : IDL.Nat,
  'status' : PropertyStatus,
  'propertyType' : PropertyType,
  'acquisitionDate' : IDL.Nat,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'estimatedCompletionDate' : IDL.Opt(IDL.Nat),
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'name' : IDL.Text,
  'dueDate' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'projectId' : IDL.Nat,
  'priority' : TaskPriority,
  'assignedTeamMember' : IDL.Opt(IDL.Principal),
});
export const TeamMember = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'projectIds' : IDL.Vec(IDL.Nat),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'department' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTeamMember' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'createProperty' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        PropertyType,
        PropertyStatus,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Nat],
      [],
    ),
  'createTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Principal),
        TaskStatus,
        TaskPriority,
        IDL.Opt(IDL.Nat),
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'deleteProperty' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(DevelopmentProject)], ['query']),
  'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(DevelopmentProject)], ['query']),
  'getProperty' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
  'getTeamMember' : IDL.Func([IDL.Principal], [IDL.Opt(TeamMember)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeTeamMember' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProject' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Bool],
      [],
    ),
  'updateProperty' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        PropertyType,
        PropertyStatus,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Bool],
      [],
    ),
  'updateTask' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Principal),
        TaskStatus,
        TaskPriority,
        IDL.Opt(IDL.Nat),
        IDL.Nat,
      ],
      [IDL.Bool],
      [],
    ),
  'updateTeamMember' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat)],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'commercial' : IDL.Null,
    'residential' : IDL.Null,
    'mixedUse' : IDL.Null,
  });
  const PropertyStatus = IDL.Variant({
    'completed' : IDL.Null,
    'development' : IDL.Null,
    'planning' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const TaskPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const DevelopmentProject = IDL.Record({
    'id' : IDL.Nat,
    'currentPhase' : IDL.Text,
    'targetCompletionDate' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'propertyId' : IDL.Nat,
    'budget' : IDL.Nat,
    'startDate' : IDL.Nat,
  });
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'status' : PropertyStatus,
    'propertyType' : PropertyType,
    'acquisitionDate' : IDL.Nat,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'estimatedCompletionDate' : IDL.Opt(IDL.Nat),
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'name' : IDL.Text,
    'dueDate' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'projectId' : IDL.Nat,
    'priority' : TaskPriority,
    'assignedTeamMember' : IDL.Opt(IDL.Principal),
  });
  const TeamMember = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'projectIds' : IDL.Vec(IDL.Nat),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'department' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTeamMember' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'createProperty' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          PropertyType,
          PropertyStatus,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Nat],
        [],
      ),
    'createTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Principal),
          TaskStatus,
          TaskPriority,
          IDL.Opt(IDL.Nat),
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'deleteProperty' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(DevelopmentProject)], ['query']),
    'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(DevelopmentProject)],
        ['query'],
      ),
    'getProperty' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
    'getTeamMember' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(TeamMember)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeTeamMember' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProject' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Bool],
        [],
      ),
    'updateProperty' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          PropertyType,
          PropertyStatus,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Bool],
        [],
      ),
    'updateTask' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Principal),
          TaskStatus,
          TaskPriority,
          IDL.Opt(IDL.Nat),
          IDL.Nat,
        ],
        [IDL.Bool],
        [],
      ),
    'updateTeamMember' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat)],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };